server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./zmen
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.zmen.backend: INFO
    org.springframework.security: DEBUG

