spring:
  application:
    name: zmen-backend
  
  datasource:
    url: jdbc:sqlite:zmen.db
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# JWT
app:
  jwt:
    secret: zmen-secret-key-2024
    expiration: 86400000

